version: "3"
volumes:
  chromium-home:
  thirdplanet-workspace:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  srv-bin:
    external:
      name: ${BIN}
services:
  chromium:
    image: urgemerge/chromium-pulseaudio
    privileged: true
    tty: true
    shm_size: "256m"
    environment:
      - DISPLAY=unix$DISPLAY
      - TARGETUID=${HOST_UID}
      - XDG_RUNTIME_DIR=/run/user/${HOST_UID}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - /run/user/${HOST_UID}/pulse:/run/user/${HOST_UID}/pulse:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket:ro
      - /var/lib/dbus:/var/lib/dbus:ro
      - /tmp:/tmp
      - /home/${HOST_USER}:/home/chromium/.config/pulse:ro
      - chromium-home:/data
      - /dev/video0:/dev/video:ro
  thirdplanet:
    image: tidyrailroad/cloud9:5.0.0
    volumes:
      - thirdplanet-workspace:/workspace
      - srv-bin:/root/bin:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    working_dir: /workspace
    command: --listen 0.0.0.0 -w /workspace --auth user:password
  gitlab:
    image: gitlab/gitlab-ce:9.0.5-ce.0
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      - /etc/localtime:/etc/localtime:ro