version: "3"
volumes:
  chromium-home:
  thirdplanet-home:
  thirdplanet-workspace:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  srv-entrypoint:
    external:
      name: ${ENTRYPOINT}
services:
  chromium:
    image: tidyrailroad/chromium:0.0.0
    privileged: true
    environment:
      - DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
      - chromium-home:/root
  thirdplanet:
    image: tidyrailroad/cloud9:5.0.0
    volumes:
      - thirdplanet-home:/root
      - thirdplanet-workspace:/workspace
      - srv-entrypoint:/srv/thirdplanet
    working_dir: /workspace
    command: --listen 0.0.0.0 -w /workspace --auth user:password
  gitlab:
    image: gitlab/gitlab-ce:9.0.5-ce.0
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      - /etc/localtime:/etc/localtime:ro